KoolStuff-Database-Working-Email/KoolStuff/Controllers/CheckoutController.cs
using KoolStuff.Data;
using KoolStuff.Models;
using Microsoft.AspNetCore.Mvc;
using Stripe.Checkout;
using System.Collections.Generic;
                            // Working with database
namespace KoolStuff.Controllers
{
    public class CheckoutController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CheckoutController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            List<Product> productList = _context.Product.ToList();
            return View(productList);
        }

        //public List<Product> ProductList { get; private set; }

        //public CheckoutController()
        //{
        //    // Initialize ProductList
        //    ProductList = new List<Product>
        //{
        //    new Product
        //    {
        //        Image = "/BatmanT.jpg",
        //        Name = "Batman-T",
        //        Description = "Character T-Shirt",
        //        Price = 12,
        //        Quantity = 1
        //    },
        //    new Product
        //    {
        //        Image = "/LokiT.jpg",
        //        Name = "Loki-T",
        //        Description = "Character T-Shirt",
        //        Price = 17,
        //        Quantity = 2
        //    },
        //    new Product
        //    {
        //        Image = "/JokerT.jpg",
        //        Name = "Joker-T",
        //        Description = "Character T-Shirt",
        //        Price = 19,
        //        Quantity = 1
        //    }
        //};
        //}

        //public IActionResult Index()
        //{
        //    // You can directly return the ProductList
        //    return View(ProductList);
        //}

        public IActionResult Checkout()
        {
            // This uses the ProductList directly
            var domain = "http://localhost:5049/";
            var options = new SessionCreateOptions
            {
                SuccessUrl = domain + "Checkout/OrderConfirmation",
                CancelUrl = domain + "Checkout/Login",
                LineItems = new List<SessionLineItemOptions>(),
                Mode = "payment"
            };
            List<Product> productList = _context.Product.ToList();
            foreach (var item in productList)
            {
                int priceInCents = (int)(item.Price * 100);

                var sessionListItem = new SessionLineItemOptions
                {
                    PriceData = new SessionLineItemPriceDataOptions
                    {
                        UnitAmount = priceInCents,
                        Currency = "cad",
                        ProductData = new SessionLineItemPriceDataProductDataOptions
                        {
                            Name = item.Name.ToString(),
                        }
                    },
                    Quantity = item.Quantity
                };
                options.LineItems.Add(sessionListItem);
            }
            // This creates a new Stripe session using the provided options
            var service = new SessionService();
            Session session = service.Create(options);

            // This redirects to the Stripe page
            return Redirect(session.Url);  
        }
    }
}

KoolStuff-Database-Working-Email/KoolStuff/Controllers/ProductsController.cs
using KoolStuff.Data;
using KoolStuff.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace KoolStuff.Controllers
{
    public class ProductsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProductsController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            List<Product> productList = _context.Product.ToList();
            return View(productList);
        }


        // GET: Products/Create
        public IActionResult Create()
        {
            ViewData["Id"] = new SelectList(_context.Product, "Id", "Name");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,Quantity,Price,Image")] Product product)
        {
            if (ModelState.IsValid)
            {
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Id"] = new SelectList(_context.Product, "Id", "Name", product.Id);
            return View(product);
        }

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Product, "Id", "Name", product.Id);
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,Quantity,Price,Image")] Product product)
        {
            if (id != product.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Id"] = new SelectList(_context.Product, "Id", "Name", product.Id);
            return View(product);
        }


        public IActionResult Details()
        {
            return View();
        }

        // GET: Products/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product
                //.Include(p => p.Id)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Product.FindAsync(id);
            if (product != null)
            {
                _context.Product.Remove(product);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _context.Product.Any(e => e.Id == id);
        }
    }
}

KoolStuff-Database-Working-Email/KoolStuff/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

        @inject SignInManager<IdentityUser> SignInManager

        @inject UserManager<IdentityUser> UserManager

<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>@ViewData["Title"] - KoolStuff</title>
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
<link rel="stylesheet" href="~/KoolStuff.styles.css" asp-append-version="true" />

@if (SignInManager.IsSignedIn(User))
{


   

                    @*Stripe Works on this one*@

            <nav class="navbar navbar-expand-lg bg-light border-bottom box-shadow mb-3" data-bs-theme="light">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">KoolStuff</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01"
                        aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Checkout" asp-action="Index">Checkout list</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Home/Stuff">Stuff</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" href="/Home/About">Featured</a>
                        </li>
                    <li class="nav-item">
                        <a class="nav-link" href="https://localhost:7130/EmailStore/Create">Newsletter</a>
                    </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button"
                           aria-haspopup="true" aria-expanded="false">Products</a>
                            <div class="dropdown-menu">
                            <a class="dropdown-item" asp-controller="Home" asp-action="List">List</a>
                            <a class="dropdown-item" asp-controller="Products" asp-action="Create">Create</a>
                                <a class="dropdown-item" href="#">Something else here</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Separated link</a>
                            </div>
                        </li>
                    </ul>
              
                    <form class="d-flex">
                        <input class="form-control me-sm-2" type="search" placeholder="Search">
                        <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form>
                   
                    <div>
                        <partial name="_LoginPartial" />
                    </div>

                </div>
            </div>
        </nav>

 
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - KoolStuff - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <script src="https://kit.fontawesome.com/c94ee1266b.js" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

}
else
{
  
            <nav class="navbar navbar-expand-lg bg-primary border-bottom box-shadow mb-3" data-bs-theme="dark">
                <div class="container-fluid">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">KoolStuff</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01"
                            aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarColor01">
                        <ul class="navbar-nav me-auto">
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Checkout" asp-action="Index">Checkout list</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="/Home/Stuff">Stuff</a>
                            </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Home/About">Featured</a>
                    <li class="nav-item">
                        <a class="nav-link" href="https://localhost:7130/EmailStore/Create">Newsletter</a>
                    </li>
                            <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="List">Table</a>
                            </li>
                        
                        </ul>
          @*       <div>
                    <a class="cartname" href="/Home/Cart"><i class="fa-solid fa-cart-shopping text-light"></i>  <br /> </a>
                </div> *@
 
                
                        <form class="d-flex">  
                            <input class="form-control me-sm-2" type="search" placeholder="Search">
                            <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Search</button>
                        </form>

                        <div>
                            <partial name="_LoginPartial" />
                        </div>

                    </div>
                </div>
            </nav>

     
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2024 - KoolStuff - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
        <script src="https://kit.fontawesome.com/c94ee1266b.js" crossorigin="anonymous"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @await RenderSectionAsync("Scripts", required: false)
   
}